name: Linting and style checking

on: [push, pull_request]

jobs:
  stylua:
    name: stylua
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: JohnnyMorganz/stylua-action@1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # CLI arguments
          args: --color always --check .
  gendoc:
    name: gendoc
    runs-on: ubuntu-20.04
    steps:
      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        id: neovim
        with:
          neovim: true
      - uses: actions/checkout@v2
      - name: Generate documentation
        run: make --silent documentation
      - name: Check for changes
        run: if [[ -n $(git status -s) ]]; then exit 1; fi
